/*


Find the Difference


Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
	Input:
	s = "abcd"
	t = "abcde"

	Output:
	e

	Explanation:
	'e' is the letter that was added.

@author Zixuan
@date	2016/12/2
*/
#include <vector>
using namespace std;

class Solution 
{
public:
	//Use XOR
	char findTheDifference(string s, string t) 
	{
		char r = 0;
		for (auto c : s) r ^= c;
		for (auto c : t) r ^= c;
		return r;

	}
};